// Auto-generated by @tanstack/router-vite-plugin on `vinxi dev`.
// This stub keeps the type system happy pre-install; the plugin
// overwrites it as soon as `npm install && vinxi dev` runs.
//
// Do not edit by hand. Re-generated on every dev/build.

import { createRoute } from "@tanstack/react-router";
import { Route as RootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";

const IndexRouteWithChildren = IndexRoute.update({
  path: "/",
  getParentRoute: () => RootRoute,
} as any);

export const routeTree = RootRoute.addChildren([IndexRouteWithChildren as any]);
